version: '3.9'
services:
  backend:
    build: 
      context: ./django-notes-app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3


  nginx:
    build: 
      context: ./django-notes-app/frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
    - backend
      # - frontend
      


volumes:
  db-data:
    driver: local

