version: '3.9'
services:
  backend:
    build: 
      context: ./django-notes-app
      dockerfile: Dockerfile
    container_name: djanngo_backend
    volumes:
      - static_build:/app/staticfiles
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: 
      context: ./django-notes-app/frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - frontend_build:/frontend/build

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    # image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/var/www/frontend
      - static_build:/app/staticfiles
    depends_on:
      - frontend
      - backend


volumes:
  db-data:
    driver: local
  frontend_build:
  static_build:



